### ISSUE TITLE
BulkMergeAsync gives Timeout error

### ISSUE THREAD

**Issue by iamSathishMohan** [NorthernLight1/N.EntityFramework.Extensions#88]
**Describe the bug**
BulkMergeAsync method provides timeout error for 700 record updates

```
using (var db = new HcsEntities())
{
	var dbInventories = await db.item_master.ToListAsync();
	int index = 1;
	foreach (var logicalGroup in ListHelper.SplitList(inventoryItems.ToList(), 700))
	{
		if (index > 1)
		{
			await db.BulkMergeAsync(logicalGroup, new BulkMergeOptions<InventoryItem>
			{
				CommandTimeout = 0,
				UsePermanentTable = true,
				MergeOnCondition = (s, t) => s.Sku == t.Sku
			});
			await db.SaveChangesAsync();
		}
		else
		{
			foreach (var inventory in inventories)
            {
                var dbInventory = dbInventories.Where(x => x.mf_item_number == inventory.Sku).ToList();
                if (dbInventory != null && dbInventory.Count > 0)
                {
                    foreach (var item in dbInventory)
                    {
                        item.qtyavail = inventory.RevisedQuantity;
                    }
                    inventory.FeedStatus = "SUCCESS";
                    inventory.UpdatedAt = DateTime.Now;
                }
                else
                {
                    inventory.FeedStatus = "FAILED";
                    inventory.UpdatedAt = DateTime.Now;
                }
            }

            await db.BulkMergeAsync(inventories, new BulkMergeOptions<InventoryItem>
            {
                CommandTimeout = 0,
                UsePermanentTable = true,
                MergeOnCondition = (s, t) => s.Sku == t.Sku
            });
            await db.BulkUpdateAsync(dbInventories, new BulkUpdateOptions<item_master>
            {
                CommandTimeout = 0,
                UsePermanentTable = true
            });
			
            await db.SaveChangesAsync();
		}

		index++;
	}
}
```

**Expected behavior**
BulkMerge should be successful.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome

**Error Log**
```
System.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception (0x80004005): The wait operation timed out
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery(IAsyncResult asyncResult, String endMethod, Boolean isInternal)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Core.Objects.ObjectContext.<ExecuteStoreCommandInternalAsync>d__181.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Core.Objects.ObjectContext.<ExecuteInTransactionAsync>d__156`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.<ExecuteAsyncImplementation>d__6`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Core.Objects.ObjectContext.<ExecuteStoreCommandInternalAsync>d__180.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at N.EntityFramework.Extensions.DbContextExtensionsAsync.<BulkUpdateAsync>d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at HCS.API.ApplicationService.ProductService.<BatchPriceUpdateItemMasterAsync>d__21.MoveNext() in ProductService.cs:line 976
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at HCS.API.ApplicationService.ProductService.<FullPriceSyncWithParallel>d__14.MoveNext() in ProductService.cs:line 682
ClientConnectionId:447f1cf3-f073-49e9-ac16-ba6c11c5019b
Error Number:-2,State:0,Class:11
```

**Comment by iamSathishMohan** [comment]
Also sometimes it provides following error as well. 

```
System.Data.Entity.Core.EntityException: The underlying provider failed on Rollback. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: connection
   at System.Data.Entity.Utilities.Check.NotNull[T](T value, String parameterName)
   at System.Data.Entity.Infrastructure.Interception.DbTransactionInterceptionContext.WithConnection(DbConnection connection)
   at System.Data.Entity.Infrastructure.Interception.DbTransactionDispatcher.Rollback(DbTransaction transaction, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Core.EntityClient.EntityTransaction.Rollback()
   --- End of inner exception stack trace ---
   at System.Data.Entity.Core.EntityClient.EntityTransaction.Rollback()
   at N.EntityFramework.Extensions.DbTransactionContext.Rollback()
   at N.EntityFramework.Extensions.DbContextExtensionsAsync.<InternalBulkMergeAsync>d__15`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at N.EntityFramework.Extensions.DbContextExtensionsAsync.<BulkMergeAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at HCS.API.ApplicationService.ProductService.<BatchPriceUpdateItemMasterAsync>d__21.MoveNext() in ProductService.cs:line 976
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at HCS.API.ApplicationService.ProductService.<FullPriceSyncWithParallel>d__14.MoveNext() in ProductService.cs:line 686
```

**Comment by NorthernLight1** [comment]
[iamSathishMohan],

The issue with the timeout has been addressed in v1.7.0. I did quite a bit of testing but I wasn't able to replicate the issue with transaction failing. I will review the code further and see if I can find something that would cause this. Let me know if the fix worked. If you encounter any further issue, please report them as a new issue.

**Comment by iamSathishMohan** [comment]
Thank you @NorthernLight1.. I will verify and confirm you

**Comment by iamSathishMohan** [comment]
@NorthernLight1 - Unfortunately, where you able to replicate the "The underlying provider failed on Rollback" issue ?

**Comment by NorthernLight1** [comment]
@iamSathishMohan 

I have not tried to replicate it yet, I will have to write a custom test to simulate what you are doing and see if I can re-produce it. Are you doing anything special like parallel execution? 

According to the error, the connection was null when a rollback was attempted, which had to have been initiated by an internal error in the framework. I was reading that is can occur when you call Commit() twice or Commit() followed by Rollback(). I'm not sure if that is the case here though. 

What you could try is to create an explicit transaction outside the calls, that way the framework would not manage it, but you would have to call Commit() and Rollback() functions yourself. I could also add an option to the BulkMergeOptions to make transactions optional.

I will try to test that this weekend and let you know.

**Comment by iamSathishMohan** [comment]
Yes, i did little more digging on this issue, what i am trying is trying to prepare and commit 1000 records in a batch.. Each of the batch is executing in the parallel.

**Comment by NorthernLight1** [comment]
@iamSathishMohan 

I was able to replicate the issue you are having, but it is because **I was using the same DbContext for all parallel operations** . You have to create a new instance of your DbContext for each operation because it uses one connection and it is not considered thread-safe. 

After changing the code to use a new instance of DbContext for each operation, it worked perfectly.

In the code above, why are you calling SaveChangesAsync in additional to the Bulk extension methods? These methods directly insert/update the data in the database.
