### ISSUE TITLE
BulkMergeAsync Failing with SqlException (0x80131904)

### ISSUE THREAD

**Issue by iamSathishMohan** [NorthernLight1/N.EntityFramework.Extensions#91]
**Describe the bug**
BulkMergeAsync method failing with System.Data.SqlClient.SqlException (0x80131904) exception.

```
await db.BulkMergeAsync(productItems, new BulkMergeOptions<FeedItem>
{
    CommandTimeout = 0,
    BatchSize = 1000,
    MergeOnCondition = (s, t) => s.Sku == t.Sku
});
```

**Expected behavior**
Records should get upserted into database without any exception.

**Additional context**
Exception logs
```
System.Data.SqlClient.SqlException (0x80131904): An object or column name is missing or empty. For SELECT INTO statements, verify each column has a name. For other statements, look for empty alias names. Aliases defined as "" or [] are not allowed. Change the alias to a valid name.
An object or column name is missing or empty. For SELECT INTO statements, verify each column has a name. For other statements, look for empty alias names. Aliases defined as "" or [] are not allowed. Change the alias to a valid name.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.NonQuery(DbCommand command, DbCommandInterceptionContext interceptionContext)
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteStoreCommandInternal(String commandText, Object[] parameters)
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass174_0.<ExecuteStoreCommand>b__0()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at N.EntityFramework.Extensions.DatabaseExtensions.CloneTable(Database database, String sourceTable, String destinationTable, IEnumerable`1 columnNames, String internalIdColumnName)
   at N.EntityFramework.Extensions.DbContextExtensionsAsync.<InternalBulkMergeAsync>d__15`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at N.EntityFramework.Extensions.DbContextExtensionsAsync.<BulkMergeAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at HCS.API.ApplicationService.ProductService.<LocalDbPriceAndQuantitySyncWithParallel>d__11.MoveNext() in ProductService.cs:line 297
ClientConnectionId:74d267d0-f43a-4298-9871-f1a3ecb13b6b
Error Number:1038,State:4,Class:15
```

**Comment by iamSathishMohan** [comment]
@NorthernLight1 - Could you please look into this issue and let me know the cause. It seems like a problem in CloneTable method.

**Comment by NorthernLight1** [comment]
@iamSathishMohan,

Do you have the FeedItem class so I can test this scenario?

**Comment by iamSathishMohan** [comment]
@NorthernLight1 - Sorry i missed your request on this. 

Please find the class defination for FeedItem

```
public partial class FeedItem
    {
        public string Sku { get; set; }
        public string Name { get; set; }
        public Nullable<double> Length { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Weight { get; set; }
        public double XmlPrice { get; set; }
        public double RevisedPrice { get; set; }
        public double XmlMapPrice { get; set; }
        public double RevisedMapPrice { get; set; }
        public int XmlQuantity { get; set; }
        public int RevisedQuantity { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public double OldPrice { get; set; }
        public double OldMapPrice { get; set; }
        public double OldQuantity { get; set; }
    }
```

**Comment by NorthernLight1** [comment]
@iamSathishMohan 

It sounds like the framework is not able to create the list of column names needed to insert the data. I used the class you provided and I was unable to get it to error.

I would suggest you create a test application that has only the FeedItem class in it and get it to fail, then you can provided that project to me to troubleshoot, unless you can think of a better way to track down the issue.

**Comment by NorthernLight1** [comment]
@iamSathishMohan 

Can you provide me with a description of the inheritance structure of the FeedItem class?

**Comment by iamSathishMohan** [comment]
@NorthernLight1 - There is no inheritance structure for this class. Am i misreading your request 
?

**Comment by NorthernLight1** [comment]
@iamSathishMohan,

I was trying to determine if the FeedItem has any other partial classes since it is marked partial.

**Comment by iamSathishMohan** [comment]
Based on database first approach, I have scaffolded the class using the database. That's why it marked as partial, but there isn't any other structure for this class.

**Comment by iamSathishMohan** [comment]
@NorthernLight1 - Any luck on this issue, its causing intermittant failures for me. Appreciate if you can find the root cause and provide a fix for it.
